### ISSUE TITLE
编辑框类型弹框BUG

### ISSUE THREAD

**Issue by tianguanghui** [wwmz/WMZDialog#10]
1、设置为单行时（其实是当做TextField用），内容为空时，placeholder上下显示不全。
2、设置为多行时（行数是-1），内容为空时，placeholder上下显示不全，如果继续点击键盘的删除或者直接输入文本，整个空间的上半部分View直接向下一点点变没了，按一下键盘就下移一截。

**Comment by wwmz** [comment]
-1不是设置多行呢。。。  行数要是正数呢 
 -1是内容的长度这个属性才用到呢
其他应该是解决了的

**Comment by tianguanghui** [comment]
好的呢，谢谢了😄
