### ISSUE TITLE
如何设置不在日期范围内的日期的颜色

### ISSUE THREAD

**Issue by qiandl2012** [wwmz/WMZDialog#14]
大佬，如何设置不在日期范围内的日期的颜色，如设置日期范围大于今天的，那么今天以前的日期不可选择，我想把这些不可选择的日期的颜色都设置为灰色（浅色），让使用户看起来就知道是不能选择的。

**Comment by wwmz** [comment]
> 大佬，如何设置不在日期范围内的日期的颜色，如设置日期范围大于今天的，那么今天以前的日期不可选择，我想把这些不可选择的日期的颜色都设置为灰色（浅色），让使用户看起来就知道是不能选择的。

我提交了demo 自定义日历里有类似的实现方式
