### ISSUE TITLE
DialogTypeWrite 下 点击ok 回调两次wEventOKFinish

### ISSUE THREAD

**Issue by PPFSaber** [wwmz/WMZDialog#15]
DialogTypeWrite 下 点击ok 回调两次wEventOKFinish  原因应该是 WMZDialog+Write 中 这一个方法错误的调用了 writeOKAction:nil
//点击Return键键盘退出
- (void)textViewDidEndEditing:(UITextView *)textView {
    if (textView == self.writeView) {
        if (self.wWirteTextMaxLine == 1) {
            [self writeOKAction:nil];
        }
    }
}

**Comment by wwmz** [comment]
> DialogTypeWrite 下 点击ok 回调两次wEventOKFinish 原因应该是 WMZDialog+Write 中 这一个方法错误的调用了 writeOKAction:nil
> //点击Return键键盘退出
> 
> * (void)textViewDidEndEditing:(UITextView *)textView {
>   if (textView == self.writeView) {
>   if (self.wWirteTextMaxLine == 1) {
>   [self writeOKAction:nil];
>   }
>   }
>   }

好的 感谢提出 修改了
