### ISSUE TITLE
无级限分类，如何动态加载每一层数据

### ISSUE THREAD

**Issue by qiandl2012** [wwmz/WMZDialog#16]
无级限分类，如何动态加载每一层数据
我通过调用updateMenuChildrenDataWithSection方法，不会更新下一级数据。

**Comment by wwmz** [comment]
> 无级限分类，如何动态加载每一层数据
> 我通过调用updateMenuChildrenDataWithSection方法，不会更新下一级数据。

调用这个方法可以的 你可以看我demo

**Comment by qiandl2012** [comment]
我的意思是像京东选择省市区那样，数据是从后台读取的，不是固定的区域数据库。
先读省份，然后选择省份后再调用API加载市级数据，选择市级再根据市级id中载区级数据。
我看了您的demo，如果设置数据源时，只设置省一级（不包含市级、区级的数据），选择某个省份后，然后调用
updateMenuChildrenDataWithSection方法入参对应省份下的市级数据，但UI不会刷新显示出市级数据。’
麻烦您看一下，谢谢。

**Comment by wwmz** [comment]
> 我的意思是像京东选择省市区那样，数据是从后台读取的，不是固定的区域数据库。
> 先读省份，然后选择省份后再调用API加载市级数据，选择市级再根据市级id中载区级数据。
> 我看了您的demo，如果设置数据源时，只设置省一级（不包含市级、区级的数据），选择某个省份后，然后调用
> updateMenuChildrenDataWithSection方法入参对应省份下的市级数据，但UI不会刷新显示出市级数据。’
> 麻烦您看一下，谢谢。

你数据源设置3层 不可以吗 用@{}替代 先占位
