### ISSUE TITLE
DialogTypePop类型时，传入wTapViewSet(temp)视图位置快速点击会出现多个pop视图

### ISSUE THREAD

**Issue by hooyking** [wwmz/WMZDialog#17]

**Comment by hooyking** [comment]
就在使用了.wShowAnimationSet()且不为AninatonShowNone时

**Comment by wwmz** [comment]
> 就在使用了.wShowAnimationSet()且不为AninatonShowNone时

我找时间再修改一下

**Comment by wwmz** [comment]
> 就在使用了.wShowAnimationSet()且不为AninatonShowNone时
GitHub已更新了

**Comment by wwmz** [comment]
> 就在使用了.wShowAnimationSet()且不为AninatonShowNone时
GitHub已更新了 新增wTag属性 设置tag即可
