### ISSUE TITLE
选择年月日 默认时间初始时间不正确

### ISSUE THREAD

**Issue by wtg934614282** [wwmz/WMZDialog#18]
修改默认时间不争取

**Comment by wtg934614282** [comment]
Dialog()
             .wEventOKFinishSet(^(id anyID, id otherData) {

             })
             //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
             .wDateTimeTypeSet(@"yyyy-MM-dd")
     //        .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
             //最小时间
    .wTitleSet(@"")
    .wPickRepeatSet(NO)
//    .wselectt
//    .wDefaultDateSet(defaultValueDate)
             .wMinDateSet(minDate)
             //最大时间
             .wMaxDateSet(maxDate)
             .wTypeSet(DialogTypeDatePicker)
             .wStart();  用法如此，默认时间不正确

**Comment by wwmz** [comment]
> ```
>   Dialog()
>          .wEventOKFinishSet(^(id anyID, id otherData) {
> 
>          })
>          //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
>          .wDateTimeTypeSet(@"yyyy-MM-dd")
>  //        .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
>          //最小时间
> .wTitleSet(@"")
> .wPickRepeatSet(NO)
> ```
> 
> // .wselectt
> // .wDefaultDateSet(defaultValueDate)
> .wMinDateSet(minDate)
> //最大时间
> .wMaxDateSet(maxDate)
> .wTypeSet(DialogTypeDatePicker)
> .wStart(); 用法如此，默认时间不正确

你把你的值也要发来哦 不然我没法给你看原因

**Comment by wtg934614282** [comment]
设置最小时间为今日5月28日，最大时间往后2年2022年5月28日，设置默认时间，默认时间为5月30日。然后就出问题了。你看看

**Comment by wtg934614282** [comment]
感觉是计算月的和日的计算当前日期的时候的错误，计算的不是当前选择的年月日的数据

**Comment by wwmz** [comment]
> 感觉是计算月的和日的计算当前日期的时候的错误，计算的不是当前选择的年月日的数据

嗯 今晚找个时间看了下 已解决更新了

**Comment by wtg934614282** [comment]
还是有点问题。如果选择一年后的日期，月份就没有之前的。  Dialog()
        .wEventOKFinishSet(^(id anyID, id otherData) {
            NSLog(@"选中 %@ %@",anyID,otherData);
        })
        .wDefaultDateSet([NSDate dateWithTimeIntervalSinceNow:24*60*60*365])
        //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
        .wDateTimeTypeSet(@"yyyy年MM月dd日")
//        .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
        //最小时间
        .wMinDateSet(minDate)
        //最大时间
        .wMaxDateSet(maxDate)
        .wTypeSet(DialogTypeDatePicker)
        .wStart();


你看看还是计算月的和日的计算当前日期的时候的错误，

**Comment by wwmz** [comment]
> 还是有点问题。如果选择一年后的日期，月份就没有之前的。 Dialog()
> .wEventOKFinishSet(^(id anyID, id otherData) {
> NSLog(@"选中 %@ %@",anyID,otherData);
> })
> .wDefaultDateSet([NSDate dateWithTimeIntervalSinceNow:24_60_60*365])
> //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
> .wDateTimeTypeSet(@"yyyy年MM月dd日")
> // .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
> //最小时间
> .wMinDateSet(minDate)
> //最大时间
> .wMaxDateSet(maxDate)
> .wTypeSet(DialogTypeDatePicker)
> .wStart();
> 
> 你看看还是计算月的和日的计算当前日期的时候的错误，

更新看看 这次应该修复了
