### ISSUE TITLE
DialogTypeAuto

### ISSUE THREAD

**Issue by cnfhv** [wwmz/WMZDialog#19]
DialogTypeAuto模式下，wMessageColorSet()
    .wMainBackColorSet(）这个修改为什么无效？

代码：
    Dialog().wTypeSet(DialogTypeAuto)
    .wMessageSet(@"AAAAAA")
    //自动消失时间 默认1.5
    .wMessageColorSet(DialogColor(0xCD3301))
    .wMainBackColorSet(DialogColor(0xFFFFFF))
    .wDisappelSecondSet(2)
    .wStart();

**Comment by wwmz** [comment]
> wMainBackColorSet

貌似被我手抖写死了好像 \(^o^)/~  GitHub已更新了 修改现在有效了
