### ISSUE TITLE
pod 无法安装哦~

### ISSUE THREAD

**Issue by SchNei** [wwmz/WMZDialog#2]
Installing WMZDialog (1.0.0)

[!] Error installing WMZDialog
[!] /usr/local/bin/git clone https://github.com/wwmz/WMZDialog.git /var/folders/zb/nybdvmfj7xn3l_w44p9bjsc80000gn/T/d20190926-10637-3ihw5c --template= --single-branch --depth 1 --branch 1.0.0

正克隆到 '/var/folders/zb/nybdvmfj7xn3l_w44p9bjsc80000gn/T/d20190926-10637-3ihw5c'...
fatal: unable to access 'https://github.com/wwmz/WMZDialog.git/': Empty reply from server

**Comment by wwmz** [comment]
你先在本地 pod search WMZDialog 
如果search不到 代表不是本地pod不是最新 
前往~/Library/Caches/CocoaPods/search_index.json 删除（search_index.json） 
然后继续 pod search WMZDialog  等待 应该就可以找到了

**Comment by wwmz** [comment]
> Installing WMZDialog (1.0.0)
> 
> [!] Error installing WMZDialog
> [!] /usr/local/bin/git clone https://github.com/wwmz/WMZDialog.git /var/folders/zb/nybdvmfj7xn3l_w44p9bjsc80000gn/T/d20190926-10637-3ihw5c --template= --single-branch --depth 1 --branch 1.0.0
> 
> 正克隆到 '/var/folders/zb/nybdvmfj7xn3l_w44p9bjsc80000gn/T/d20190926-10637-3ihw5c'...
> fatal: unable to access 'https://github.com/wwmz/WMZDialog.git/': Empty reply from server

你先在本地 pod search WMZDialog
如果search不到 代表不是本地pod不是最新
前往~/Library/Caches/CocoaPods/search_index.json 删除（search_index.json）
然后继续 pod search WMZDialog 等待 应该就可以找到了

**Comment by SchNei** [comment]
> > Installing WMZDialog (1.0.0)
> > [!] Error installing WMZDialog
> > [!] /usr/local/bin/git clone https://github.com/wwmz/WMZDialog.git /var/folders/zb/nybdvmfj7xn3l_w44p9bjsc80000gn/T/d20190926-10637-3ihw5c --template= --single-branch --depth 1 --branch 1.0.0
> > 正克隆到 '/var/folders/zb/nybdvmfj7xn3l_w44p9bjsc80000gn/T/d20190926-10637-3ihw5c'...
> > fatal: unable to access 'https://github.com/wwmz/WMZDialog.git/': Empty reply from server
> 
> 你先在本地 pod search WMZDialog
> 如果search不到 代表不是本地pod不是最新
> 前往~/Library/Caches/CocoaPods/search_index.json 删除（search_index.json）
> 然后继续 pod search WMZDialog 等待 应该就可以找到了

嗯按此法解决了。thx
