### ISSUE TITLE
DialogTypePop 类型，用XIB创建的按钮，点击的时候没办法正常定位到按钮位置

### ISSUE THREAD

**Issue by shwrt2016** [wwmz/WMZDialog#20]
![image](https://user-images.githubusercontent.com/19678524/85522266-fc441c00-b637-11ea-8310-7c0f0fdbe685.png)

**Comment by wwmz** [comment]
可以试一下 wTapRect这个属性呢 

//如果弹出视图的frame不准确 可以自行调节
WMZDialogStatementAndPropSetFuncStatement(assign, WMZDialog, CGRect,                   wTapRect)
