### ISSUE TITLE
多级菜单的ID获取不到值

### ISSUE THREAD

**Issue by 91geek** [wwmz/WMZDialog#21]
WMZTree这个类里面定义的是大写的ID，在点击事件中的字典里面又是用@“id”去拿值，这个会取到空。无法获取到id的值。

**Comment by wwmz** [comment]
> WMZTree这个类里面定义的是大写的ID，在点击事件中的字典里面又是用@“id”去拿值，这个会取到空。无法获取到id的值。

传值用小写即可
