### ISSUE TITLE
DialogTypeMyView 自定义弹窗不支持约束布局吗？用masonry布局有各种问题

### ISSUE THREAD

**Issue by huangzhaohao** [wwmz/WMZDialog#22]

**Comment by wwmz** [comment]
> _No description provided._

嗯？是什么问题？支持的呀

**Comment by huangzhaohao** [comment]
`//自定义优酷方法
- (void)youkuDialog{
    __weak CustomVC *WEAK = self;
    myAlert = Dialog()
    .wTypeSet(DialogTypeMyView)
    //关闭事件 此时要置为不然会内存泄漏
    .wEventCloseSet(^(id anyID, id otherData) {
        myAlert = nil;
    })
    .wShowAnimationSet(AninatonZoomIn)
    .wHideAnimationSet(AninatonZoomOut)
    .wMyDiaLogViewSet(^UIView *(UIView *mainView) {
        UIImageView *image = [UIImageView new];
        image.image = [UIImage imageNamed:@"healthy"];
//        image.frame = CGRectMake(0, 0, mainView.frame.size.width, 80);
        [mainView addSubview:image];
        [image mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.left.mas_equalTo(mainView);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 80));
        }];
        
        UILabel *la = [UILabel new];
        la.font = [UIFont systemFontOfSize:15.0f];
        la.text = @"为呵护未成年人健康成长,优酷特别推出青少年模式,该模式下部分功能无法正常使用,请监护人主动选择，并设置监护密码";
        la.numberOfLines = 0;
//        la.frame = CGRectMake(10, CGRectGetMaxY(image.frame), mainView.frame.size.width-20, 100);
        [mainView addSubview:la];
        [la mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView).offset(10);
            make.top.mas_equalTo(image.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width-20, 100));
        }];
        
        
        UIButton *enter = [UIButton buttonWithType:UIButtonTypeCustom];
        [mainView addSubview:enter];
        enter.titleLabel.font = [UIFont systemFontOfSize:14.0f];
//        enter.frame = CGRectMake(0, CGRectGetMaxY(la.frame), mainView.frame.size.width, 44);
        [enter setTitle:@"进入青少年模式 >" forState:UIControlStateNormal];
        [enter setTitleColor:DialogColor(0x108ee9) forState:UIControlStateNormal];
        [enter addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
        [enter mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView);
            make.top.mas_equalTo(la.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
        }];
        
        UIButton *know = [UIButton buttonWithType:UIButtonTypeCustom];
        [mainView addSubview:know];
        know.titleLabel.font = [UIFont systemFontOfSize:14.0f];
//        know.frame = CGRectMake(0, CGRectGetMaxY(enter.frame), mainView.frame.size.width, 44);
        [know setTitle:@"我知道了" forState:UIControlStateNormal];
        [know setTitleColor:DialogColor(0x3333333) forState:UIControlStateNormal];
        [know addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
        [know mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView);
            make.top.mas_equalTo(enter.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
        }];
        
        mainView.layer.masksToBounds = YES;
        mainView.layer.cornerRadius = 10;
        return know;
    })
    .wStart();
}`
![1101597988897_ pic](https://user-images.githubusercontent.com/23187644/90856667-0a52b680-e3b5-11ea-8a06-bc5a59163c18.jpg)
显示不全，高度不对，我试着改了下demo里的会显示成这样

**Comment by huangzhaohao** [comment]
`
//自定义优酷方法
- (void)youkuDialog{
    __weak CustomVC *WEAK = self;
    myAlert = Dialog()
    .wTypeSet(DialogTypeMyView)
    //关闭事件 此时要置为不然会内存泄漏
    .wEventCloseSet(^(id anyID, id otherData) {
        myAlert = nil;
    })
    .wShowAnimationSet(AninatonZoomIn)
    .wHideAnimationSet(AninatonZoomOut)
    .wMyDiaLogViewSet(^UIView *(UIView *mainView) {
        UIImageView *image = [UIImageView new];
        image.image = [UIImage imageNamed:@"healthy"];
//        image.frame = CGRectMake(0, 0, mainView.frame.size.width, 80);
        [mainView addSubview:image];
        [image mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.left.mas_equalTo(mainView);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 80));
        }];
        
        UILabel *la = [UILabel new];
        la.font = [UIFont systemFontOfSize:15.0f];
        la.text = @"为呵护未成年人健康成长,优酷特别推出青少年模式,该模式下部分功能无法正常使用,请监护人主动选择，并设置监护密码";
        la.numberOfLines = 0;
//        la.frame = CGRectMake(10, CGRectGetMaxY(image.frame), mainView.frame.size.width-20, 100);
        [mainView addSubview:la];
        [la mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView).offset(10);
            make.top.mas_equalTo(image.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width-20, 100));
        }];
        
        
        UIButton *enter = [UIButton buttonWithType:UIButtonTypeCustom];
        [mainView addSubview:enter];
        enter.titleLabel.font = [UIFont systemFontOfSize:14.0f];
//        enter.frame = CGRectMake(0, CGRectGetMaxY(la.frame), mainView.frame.size.width, 44);
        [enter setTitle:@"进入青少年模式 >" forState:UIControlStateNormal];
        [enter setTitleColor:DialogColor(0x108ee9) forState:UIControlStateNormal];
        [enter addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
        [enter mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView);
            make.top.mas_equalTo(la.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
        }];
        
        UIButton *know = [UIButton buttonWithType:UIButtonTypeCustom];
        [mainView addSubview:know];
        know.titleLabel.font = [UIFont systemFontOfSize:14.0f];
//        know.frame = CGRectMake(0, CGRectGetMaxY(enter.frame), mainView.frame.size.width, 44);
        [know setTitle:@"我知道了" forState:UIControlStateNormal];
        [know setTitleColor:DialogColor(0x3333333) forState:UIControlStateNormal];
        [know addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
        [know mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView);
            make.top.mas_equalTo(enter.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
        }];
        
        mainView.layer.masksToBounds = YES;
        mainView.layer.cornerRadius = 10;
        return know;
    })
    .wStart();
}
`
![1101597988897_ pic](https://user-images.githubusercontent.com/23187644/90857156-1be88e00-e3b6-11ea-8e29-57db44a4e13c.jpg)
显示不全，高度不对，我试着改了下demo里的会显示成这样

**Comment by huangzhaohao** [comment]
//自定义优酷方法
- (void)youkuDialog{
    __weak CustomVC *WEAK = self;
    myAlert = Dialog()
    .wTypeSet(DialogTypeMyView)
    //关闭事件 此时要置为不然会内存泄漏
    .wEventCloseSet(^(id anyID, id otherData) {
        myAlert = nil;
    })
    .wShowAnimationSet(AninatonZoomIn)
    .wHideAnimationSet(AninatonZoomOut)
    .wMyDiaLogViewSet(^UIView *(UIView *mainView) {
        UIImageView *image = [UIImageView new];
        image.image = [UIImage imageNamed:@"healthy"];
//        image.frame = CGRectMake(0, 0, mainView.frame.size.width, 80);
        [mainView addSubview:image];
        [image mas_makeConstraints:^(MASConstraintMaker *make) {
            make.top.left.mas_equalTo(mainView);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 80));
        }];
        
        UILabel *la = [UILabel new];
        la.font = [UIFont systemFontOfSize:15.0f];
        la.text = @"为呵护未成年人健康成长,优酷特别推出青少年模式,该模式下部分功能无法正常使用,请监护人主动选择，并设置监护密码";
        la.numberOfLines = 0;
//        la.frame = CGRectMake(10, CGRectGetMaxY(image.frame), mainView.frame.size.width-20, 100);
        [mainView addSubview:la];
        [la mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView).offset(10);
            make.top.mas_equalTo(image.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width-20, 100));
        }];
        
        
        UIButton *enter = [UIButton buttonWithType:UIButtonTypeCustom];
        [mainView addSubview:enter];
        enter.titleLabel.font = [UIFont systemFontOfSize:14.0f];
//        enter.frame = CGRectMake(0, CGRectGetMaxY(la.frame), mainView.frame.size.width, 44);
        [enter setTitle:@"进入青少年模式 >" forState:UIControlStateNormal];
        [enter setTitleColor:DialogColor(0x108ee9) forState:UIControlStateNormal];
        [enter addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
        [enter mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView);
            make.top.mas_equalTo(la.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
        }];
        
        UIButton *know = [UIButton buttonWithType:UIButtonTypeCustom];
        [mainView addSubview:know];
        know.titleLabel.font = [UIFont systemFontOfSize:14.0f];
//        know.frame = CGRectMake(0, CGRectGetMaxY(enter.frame), mainView.frame.size.width, 44);
        [know setTitle:@"我知道了" forState:UIControlStateNormal];
        [know setTitleColor:DialogColor(0x3333333) forState:UIControlStateNormal];
        [know addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
        [know mas_makeConstraints:^(MASConstraintMaker *make) {
            make.left.mas_equalTo(mainView);
            make.top.mas_equalTo(enter.mas_bottom);
            make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
        }];
        
        mainView.layer.masksToBounds = YES;
        mainView.layer.cornerRadius = 10;
        return know;
    })
    .wStart();
}

![1101597988897_ pic](https://user-images.githubusercontent.com/23187644/90857243-49353c00-e3b6-11ea-8b1c-ff994109c6e6.jpg)
显示不全，高度不对，我试着改了下demo里的会显示成这样

**Comment by wwmz** [comment]
> //自定义优酷方法
> 
> * (void)youkuDialog{
>   __weak CustomVC *WEAK = self;
>   myAlert = Dialog()
>   .wTypeSet(DialogTypeMyView)
>   //关闭事件 此时要置为不然会内存泄漏
>   .wEventCloseSet(^(id anyID, id otherData) {
>   myAlert = nil;
>   })
>   .wShowAnimationSet(AninatonZoomIn)
>   .wHideAnimationSet(AninatonZoomOut)
>   .wMyDiaLogViewSet(^UIView *(UIView *mainView) {
>   UIImageView *image = [UIImageView new];
>   image.image = [UIImage imageNamed:@"healthy"];
>   //        image.frame = CGRectMake(0, 0, mainView.frame.size.width, 80);
>   [mainView addSubview:image];
>   [image mas_makeConstraints:^(MASConstraintMaker *make) {
>   make.top.left.mas_equalTo(mainView);
>   make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 80));
>   }];
>   ```
>     UILabel *la = [UILabel new];
>     la.font = [UIFont systemFontOfSize:15.0f];
>     la.text = @"为呵护未成年人健康成长,优酷特别推出青少年模式,该模式下部分功能无法正常使用,请监护人主动选择，并设置监护密码";
>     la.numberOfLines = 0;
>   ```
> 
> // la.frame = CGRectMake(10, CGRectGetMaxY(image.frame), mainView.frame.size.width-20, 100);
> [mainView addSubview:la];
> [la mas_makeConstraints:^(MASConstraintMaker *make) {
> make.left.mas_equalTo(mainView).offset(10);
> make.top.mas_equalTo(image.mas_bottom);
> make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width-20, 100));
> }];
> 
> ```
>     UIButton *enter = [UIButton buttonWithType:UIButtonTypeCustom];
>     [mainView addSubview:enter];
>     enter.titleLabel.font = [UIFont systemFontOfSize:14.0f];
> ```
> 
> // enter.frame = CGRectMake(0, CGRectGetMaxY(la.frame), mainView.frame.size.width, 44);
> [enter setTitle:@"进入青少年模式 >" forState:UIControlStateNormal];
> [enter setTitleColor:DialogColor(0x108ee9) forState:UIControlStateNormal];
> [enter addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
> [enter mas_makeConstraints:^(MASConstraintMaker *make) {
> make.left.mas_equalTo(mainView);
> make.top.mas_equalTo(la.mas_bottom);
> make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
> }];
> 
> ```
>     UIButton *know = [UIButton buttonWithType:UIButtonTypeCustom];
>     [mainView addSubview:know];
>     know.titleLabel.font = [UIFont systemFontOfSize:14.0f];
> ```
> 
> // know.frame = CGRectMake(0, CGRectGetMaxY(enter.frame), mainView.frame.size.width, 44);
> [know setTitle:@"我知道了" forState:UIControlStateNormal];
> [know setTitleColor:DialogColor(0x3333333) forState:UIControlStateNormal];
> [know addTarget:WEAK action:@selector(youkuAction:) forControlEvents:UIControlEventTouchUpInside];
> [know mas_makeConstraints:^(MASConstraintMaker *make) {
> make.left.mas_equalTo(mainView);
> make.top.mas_equalTo(enter.mas_bottom);
> make.size.mas_equalTo(CGSizeMake(mainView.frame.size.width, 44));
> }];
> 
> ```
>     mainView.layer.masksToBounds = YES;
>     mainView.layer.cornerRadius = 10;
>     return know;
> })
> .wStart();
> ```
> 
> }
> 
> ![1101597988897_ pic](https://user-images.githubusercontent.com/23187644/90857243-49353c00-e3b6-11ea-8b1c-ff994109c6e6.jpg)
> 显示不全，高度不对，我试着改了下demo里的会显示成这样

可以加下q群代码发我看看~ ~ 这想复制过去都难 937909825

**Comment by wwmz** [comment]
此问题的 最后面调用一下[mainView layoutIfNeeded] 即可
