### ISSUE TITLE
老哥日历弹窗能否做时间段连在一起的效果类似FSCalendar的这种

### ISSUE THREAD

**Issue by jianjianhao** [wwmz/WMZDialog#23]
FSCalendar之前用了一段时间，后来发现bug很多作者不维护了，哎，现在看到这么多弹窗的轮子，还是膜拜下吧，毕竟维护才是最难的

**Comment by wwmz** [comment]
> FSCalendar之前用了一段时间，后来发现bug很多作者不维护了，哎，现在看到这么多弹窗的轮子，还是膜拜下吧，毕竟维护才是最难的

啥效果。。有图吗 是呀。。造轮子容易 维护难。。。

**Comment by jianjianhao** [comment]
![22354a0e-a342-11e6-8ae6-0614ea7f35ae](https://user-images.githubusercontent.com/12797357/93308707-2ff8a180-f835-11ea-983b-f37229c94884.gif)
不知道能不能看到图片，就是一段日期连在一起

**Comment by wwmz** [comment]
> ![22354a0e-a342-11e6-8ae6-0614ea7f35ae](https://user-images.githubusercontent.com/12797357/93308707-2ff8a180-f835-11ea-983b-f37229c94884.gif)
> 不知道能不能看到图片，就是一段日期连在一起

哦哦 是这样啊 如果相邻两行连在一起呢 是啥效果

**Comment by jianjianhao** [comment]
![Simulator Screen Shot - iPhone 8 - 2020-09-16 at 16 00 46](https://user-images.githubusercontent.com/12797357/93309197-cd53d580-f835-11ea-9138-f35580d84111.png)

**Comment by jianjianhao** [comment]
不过加太多功能可能会对这个弹窗框架负担过大

**Comment by wwmz** [comment]
> 不过加太多功能可能会对这个弹窗框架负担过大

分开的。。不互相影响的。。随便可扩展的。

**Comment by wwmz** [comment]
> 不过加太多功能可能会对这个弹窗框架负担过大

时间隔得有点久哈。。1.2.0 已加上
