### ISSUE TITLE
日期选择器 设置最大日期后，最大日期后面的还是可以选

### ISSUE THREAD

**Issue by Want2Free** [wwmz/WMZDialog#26]
当默认日期与最大日期一致时，最大日期后面的日期还是可以选。如当前是12.2日，默认日期是12.2日，但12.2日之后的日期还是可以选。切换月份 - 重新选择12月时才会刷新2号后的日期不可选。
   .wDateTimeTypeSet(@"yyyy-MM-dd")
   .wPickRepeatSet(NO)
    .wMaxDateSet([NSDate date])
    .wDefaultDateSet([NSDate date])
    .wMinDateSet([[NSDate date] dateByAddingYears:-1])

**Comment by wwmz** [comment]
> 当默认日期与最大日期一致时，最大日期后面的日期还是可以选。如当前是12.2日，默认日期是12.2日，但12.2日之后的日期还是可以选。切换月份 - 重新选择12月时才会刷新2号后的日期不可选。
> .wDateTimeTypeSet(@"yyyy-MM-dd")
> .wPickRepeatSet(NO)
> .wMaxDateSet([NSDate date])
> .wDefaultDateSet([NSDate date])
> .wMinDateSet([[NSDate date] dateByAddingYears:-1])

更新最新版本1.1.9 你pod的版本应该不是最新的

**Comment by Want2Free** [comment]
已经是最新版本了呀！发自我的iPhone------------------ 原始邮件 ------------------发件人: WMZ  <notifications@github.com>发送时间: 2020年12月3日 21:09收件人: wwmz/WMZDialog <WMZDialog@noreply.github.com>抄送: Want2Free <hjs8906@163.com>, Author <author@noreply.github.com>主题: 回复：[wwmz/WMZDialog] 日期选择器 设置最大日期后，最大日期后面的还是可以选 (#26)

当默认日期与最大日期一致时，最大日期后面的日期还是可以选。如当前是12.2日，默认日期是12.2日，但12.2日之后的日期还是可以选。切换月份 - 重新选择12月时才会刷新2号后的日期不可选。
.wDateTimeTypeSet(@"yyyy-MM-dd")
.wPickRepeatSet(NO)
.wMaxDateSet([NSDate date])
.wDefaultDateSet([NSDate date])
.wMinDateSet([[NSDate date] dateByAddingYears:-1])

更新最新版本1.1.9 你pod的版本应该不是最新的

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/wwmz/WMZDialog/issues/26#issuecomment-737973400",
"url": "https://github.com/wwmz/WMZDialog/issues/26#issuecomment-737973400",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by wwmz** [comment]
> 已经是最新版本了呀！发自我的iPhone------------------ 原始邮件 ------------------发件人: WMZ <notifications@github.com>发送时间: 2020年12月3日 21:09收件人: wwmz/WMZDialog <WMZDialog@noreply.github.com>抄送: Want2Free <hjs8906@163.com>, Author <author@noreply.github.com>主题: 回复：[wwmz/WMZDialog] 日期选择器 设置最大日期后，最大日期后面的还是可以选 (#26) 当默认日期与最大日期一致时，最大日期后面的日期还是可以选。如当前是12.2日，默认日期是12.2日，但12.2日之后的日期还是可以选。切换月份 - 重新选择12月时才会刷新2号后的日期不可选。 .wDateTimeTypeSet(@"yyyy-MM-dd") .wPickRepeatSet(NO) .wMaxDateSet([NSDate date]) .wDefaultDateSet([NSDate date]) .wMinDateSet([[NSDate date] dateByAddingYears:-1]) 更新最新版本1.1.9 你pod的版本应该不是最新的 —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#26 (comment)](https://github.com/wwmz/WMZDialog/issues/26#issuecomment-737973400)", "url": "[#26 (comment)](https://github.com/wwmz/WMZDialog/issues/26#issuecomment-737973400)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

我运行demo正常啊。。 后面的日期选不了 。。
