### ISSUE TITLE
popView的三角形宽高改变

### ISSUE THREAD

**Issue by wangchaoya** [wwmz/WMZDialog#27]
大佬可以增加个属性改变popView的三角形的宽高吗

**Comment by wwmz** [comment]
> 大佬可以增加个属性改变popView的三角形的宽高吗

新增自定义三角形size default （20,15） 1.2.0版本有
.wAngleSizeSet(CGSizeMake(8, 8))

**Comment by wangchaoya** [comment]
辛苦大佬了，1.20版本还没出吧

**Comment by wwmz** [comment]
> 辛苦大佬了，1.20版本还没出吧

对 明天早上再更新上去哈
