### ISSUE TITLE
Undefined symbols for architecture armv7:   "Dialog()", referenced from:

### ISSUE THREAD

**Issue by mousesmalltail** [wwmz/WMZDialog#28]
请问编译的时候报这个错误是什么原因？
![image](https://user-images.githubusercontent.com/49893345/103188072-f50d0c00-4901-11eb-9e88-49c96fa3ceaf.png)

**Comment by mousesmalltail** [comment]
我也是pod安装的，然后在.mm中饮用，然后就提示Dialog()没有定义

**Comment by mousesmalltail** [comment]
> 请问编译的时候报这个错误是什么原因？
> ![image](https://user-images.githubusercontent.com/49893345/103188072-f50d0c00-4901-11eb-9e88-49c96fa3ceaf.png)

**Comment by wwmz** [comment]
> 我也是pod安装的，然后在.mm中饮用，然后就提示Dialog()没有定义

那用 WMZDialog *dialog = [[WMZDialog alloc] init] 吧

**Comment by mousesmalltail** [comment]
good
