### ISSUE TITLE
怎么设置他frame

### ISSUE THREAD

**Issue by tianjinzhong** [wwmz/WMZDialog#3]
上下左右的弹窗列表 怎么才能设置他的frame

**Comment by wwmz** [comment]
在通用属性里 有个设置wWidth的

**Comment by tianjinzhong** [comment]
能给个详细的代码么

**Comment by tianjinzhong** [comment]
&nbsp;&nbsp;Dialog().wTypeSet(DialogTypePop)
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wEventFinishSet(^(id anyID, NSIndexPath *path, DialogType type) {
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NSLog(@"%@ %@",anyID,path);
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; })
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wShowAnimationSet(AninatonZoomIn)
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wHideAnimationSet(AninatonZoomOut)
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wDirectionSet( 2 )
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wDataSet(@[
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; @{@"name":@"微信",@"image":@"wallet"},
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; @{@"name":@"支付宝",@"image":@"aaa"},
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; @{@"name":@"米聊",@"image":@"bbb"},
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; @{@"name":@"微信1",@"image":@"wallet"},
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; ])
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wTapViewSet(sender)
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; .wStart();

大佬 见附件： 这个frame y需要往下移 x需要往左边挪 框架我改了一下 改不动



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"WMZ"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 晚上7:50
收件人:&nbsp;"wwmz/WMZDialog"<WMZDialog@noreply.github.com&gt;;
抄送:&nbsp;"在路上"<452344823@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [wwmz/WMZDialog] 怎么设置他frame (#3)




在通用属性里 有个设置wWidth的

**Comment by wwmz** [comment]
加我q 925457662 我看不到啥。。。
