### ISSUE TITLE
地区选择问题

### ISSUE THREAD

**Issue by wangchaoya** [wwmz/WMZDialog#30]
地区选择的province_data.xml 可以支持外部传入吗，公司的文件的code码可能跟里面的不一样

**Comment by wwmz** [comment]
> 地区选择的province_data.xml 可以支持外部传入吗，公司的文件的code码可能跟里面的不一样

1 我里面不是贴了个自定义数据的方法吗 你可以自己解析然后把数据传进来

**Comment by wwmz** [comment]
> 地区选择的province_data.xml 可以支持外部传入吗，公司的文件的code码可能跟里面的不一样

2 code码不一样的话 你可以把整个xml文件替换掉 然后源码改下xml路径 还有 124行改下解析的key值就行了

**Comment by wangchaoya** [comment]
可以是可以，不是想复用里面那套代码，如果改成可以传入路径的，        NSString *path = [self.dialogBundle pathForResource:@"province_data" ofType:@"xml"]; 这样就更灵活一点。 这个path 可以自己传

**Comment by wwmz** [comment]
> 可以是可以，不是想复用里面那套代码，如果改成可以传入路径的， NSString *path = [self.dialogBundle pathForResource:@"province_data" ofType:@"xml"]; 这样就更灵活一点。 这个path 可以自己传

哦 你是说这个么 不过我是怕外面传进来的key值 和我取的时候对不上 就没让外面可以传进来了

**Comment by wangchaoya** [comment]
我专门让后台做的跟你的字段是一样的，现在就是在bundle替换一下

**Comment by wangchaoya** [comment]
不过我把你的代码copy一遍出去也行

**Comment by wangchaoya** [comment]
感觉这种资源文件放在 demo里面更好点，这样可替换性高一点

**Comment by wwmz** [comment]
> 我专门让后台做的跟你的字段是一样的，现在就是在bundle替换一下

哈哈 可以 那你直接替换 后面更新 swift版本的时候会一起放出来

**Comment by wangchaoya** [comment]
非常感谢！
