### ISSUE TITLE
选择弹窗有没有带确认取消按钮的

### ISSUE THREAD

**Issue by lavender1026** [wwmz/WMZDialog#31]
选择弹窗有没有带确认取消按钮的

**Comment by wwmz** [comment]
> 选择弹窗有没有带确认取消按钮的

        加这个底部就有取消按钮 不过只有多选的时候有哦    .wEventCancelFinishSet(^(id anyID, id otherData) {
                
            })

**Comment by lavender1026** [comment]
有点头疼，我们这边是扫描蓝牙设备的一个弹窗，单选且带俩选项。。。
感谢回复

**Comment by lavender1026** [comment]
我凑。。还真是，我把wMultipleSelectionSet设为yes添加底部            .wAddBottomViewSet(YES)
就出来了，但是这样没法单选啊，大哥有啥高招么

**Comment by wwmz** [comment]
> wMultipleSelectionSet
若要单选底部也有确定按钮则设置 .wAddBottomViewSet(YES) 附加取消按钮则增加.wEventCancelFinishSet(^(id anyID, id otherData) {
            
        })
