### ISSUE TITLE
怎么在弹出的时候显示在指定日期并显示那个选中状态按钮  貌似没有api

### ISSUE THREAD

**Issue by Ave838** [wwmz/WMZDialog#32]
日历弹窗怎么在弹出的时候显示在指定日期并显示那个选中状态按钮  貌似没有api

**Comment by wwmz** [comment]
> 日历弹窗怎么在弹出的时候显示在指定日期并显示那个选中状态按钮 貌似没有api

 .wDefaultDateSet([NSDate data])   //跳转到默认日期页  wListDefaultValueSet //默认选中 后面的那个属性我看了下单选的好像忘记适配了 只适配了单选的

**Comment by Ave838** [comment]
多谢，控件很全面好用。但是弹窗弹出的时候透明背景加入过渡动画，显示的时候会对体验有所提升。
WMZDialog.m  -> 524行  。
`self.shadowView.alpha = 0;
    [UIView animateWithDuration:0.3 animations:^{
        self.shadowView.alpha = self.wShadowAlpha;
    }];`

**Comment by wwmz** [comment]
> 多谢，控件很全面好用。但是弹窗弹出的时候透明背景加入过渡动画，显示的时候会对体验有所提升。
> WMZDialog.m -> 524行 。
> `self.shadowView.alpha = 0; [UIView animateWithDuration:0.3 animations:^{ self.shadowView.alpha = self.wShadowAlpha; }];`

里面有带很多动画效果的  wShowAnimation   阴影这个加这个过度也可以哈

**Comment by Ave838** [comment]
> > 多谢，控件很全面好用。但是弹窗弹出的时候透明背景加入过渡动画，显示的时候会对体验有所提升。
> > WMZDialog.m -> 524行 。
> > `self.shadowView.alpha = 0; [UIView animateWithDuration:0.3 animations:^{ self.shadowView.alpha = self.wShadowAlpha; }];`
> 
> 里面有带很多动画效果的 wShowAnimation 阴影这个加这个过度也可以哈

是半透明背景遮罩层的显示哈：wShadowColor，目前貌似是直接显示的。子弹窗是有动画可选的

**Comment by wwmz** [comment]
> > > 多谢，控件很全面好用。但是弹窗弹出的时候透明背景加入过渡动画，显示的时候会对体验有所提升。
> > > WMZDialog.m -> 524行 。
> > > `self.shadowView.alpha = 0; [UIView animateWithDuration:0.3 animations:^{ self.shadowView.alpha = self.wShadowAlpha; }];`
> > 
> > 
> > 里面有带很多动画效果的 wShowAnimation 阴影这个加这个过度也可以哈
> 
> 是半透明背景遮罩层的显示哈：wShadowColor，目前貌似是直接显示的。子弹窗是有动画可选的

嗯 加上了
