### ISSUE TITLE
XMLPathName 的bundle问题

### ISSUE THREAD

**Issue by wangchaoya** [wwmz/WMZDialog#33]
非常感谢大佬的更新，但是这个属性取的文件还是在你的bundle中，能不能直接开放个主bundle的全路径，或者我直接把文件传进去呢

**Comment by wangchaoya** [comment]
NSString *path = [self.dialogBundle pathForResource:self.wXMLPathName ofType:@"xml"];
 直接开放这个整个路径

**Comment by wwmz** [comment]
> 非常感谢大佬的更新，但是这个属性取的文件还是在你的bundle中，能不能直接开放个主bundle的全路径，或者我直接把文件传进去呢

忘记了cocopod里的bundle不一样。。等我下次更新哈

**Comment by wangchaoya** [comment]
辛苦啦
