### ISSUE TITLE
崩溃问题！

### ISSUE THREAD

**Issue by wangchaoya** [wwmz/WMZDialog#34]
新版本的DialogCell 更改了cell的获取方式 从xib 获取，但是通过cocoapods安装时候，加载不到而导致了崩溃
+(instancetype)getCell{
    return (DialogCell *)[[[WMZDialogTool getMainBundle] loadNibNamed:@"DialogCell" owner:nil options:nil] lastObject];
}
+(instancetype)getTextCell{
    return (DialogCell *)[[[WMZDialogTool getMainBundle]  loadNibNamed:@"DialogTextCell" owner:nil options:nil] lastObject];
}
+(instancetype)getImageCenterCell{
    return (DialogCell *)[[[WMZDialogTool getMainBundle] loadNibNamed:@"DialogCenterCell" owner:nil options:nil] lastObject];
}

**Comment by wangchaoya** [comment]
Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/C5586BA9-56F4-4901-A876-13D5871A44C9/nongle.app> (loaded)' with name

**Comment by wwmz** [comment]
> Could not load NIB in bundle: 'NSBundle </private/var/containers/Bundle/Application/C5586BA9-56F4-4901-A876-13D5871A44C9/nongle.app> (loaded)' with name

pod 是1.2.3吗

**Comment by wangchaoya** [comment]
是的，最新版本

**Comment by wwmz** [comment]
> 是的，最新版本

我自己集成了cocopod最新版本没问题啊 你仔细看是不是最新的

**Comment by wangchaoya** [comment]
我猜可能是framework和静态库问题，我这边用的静态库

**Comment by wangchaoya** [comment]
静态库中cocopod代码都被打包进入主二进制文件了，就找不到了

**Comment by wwmz** [comment]
> 静态库中cocopod代码都被打包进入主二进制文件了，就找不到了

好吧。。你那种估计bundle的路径 又被更换了

**Comment by wwmz** [comment]
> 静态库中cocopod代码都被打包进入主二进制文件了，就找不到了
加个xib还是有点麻烦。。。你可以调试下看bundle的路径 变成啥了

**Comment by wangchaoya** [comment]
我看有的库的方案是把xib放在自己的Resources的bundle中，这样会不会好点

**Comment by wangchaoya** [comment]
2021-01-12 14:29:46.821101+0800 xxxxxxx[2539:323102] NSBundle </private/var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app> (loaded)
2021-01-12 14:29:46.821251+0800 xxxxxxx[2539:323102] (
	NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/MJRefresh.bundle> (not yet loaded),
	NSBundle </private/var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app> (loaded),
	NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/MJRefresh.bundle/zh-Hans.lproj> (not yet loaded),
	NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/WMZDialog.bundle> (not yet loaded),
	NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/APCommonUI.bundle> (not yet loaded)
)
这是我下面获取到的   你的获取bundle 方法   和   allbundle 方法  ，都找不到 xib

**Comment by wwmz** [comment]
> 2021-01-12 14:29:46.821101+0800 xxxxxxx[2539:323102] NSBundle </private/var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app> (loaded)
> 2021-01-12 14:29:46.821251+0800 xxxxxxx[2539:323102] (
> NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/MJRefresh.bundle> (not yet loaded),
> NSBundle </private/var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app> (loaded),
> NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/MJRefresh.bundle/zh-Hans.lproj> (not yet loaded),
> NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/WMZDialog.bundle> (not yet loaded),
> NSBundle </var/containers/Bundle/Application/A87C3BE9-5F38-4D2E-BDF7-CDBF5A944A74/xxxxxxx.app/APCommonUI.bundle> (not yet loaded)
> )
> 这是我下面获取到的 你的获取bundle 方法 和 allbundle 方法 ，都找不到 xib

转成nib放进 bundle了 下午你更新下试试

**Comment by wangchaoya** [comment]
辛苦啦！

**Comment by wangchaoya** [comment]
已更新，目前都正常
