### ISSUE TITLE
弹框中的三角形，支持圆角

### ISSUE THREAD

**Issue by ygf-git** [wwmz/WMZDialog#36]
需求：弹框中的三角形，看起来很不友好

办法：我只能修改您的如下代码
    //上边
    [path moveToPoint:CGPointMake(minX+cornerRadius, minY)];
//    //三角形
//    if (direction == directionUp) {
//        [path addLineToPoint:CGPointMake(offset-width/2, minY)];
//        [path addLineToPoint:CGPointMake(offset, minY-height)];
//        [path addLineToPoint:CGPointMake(offset+width/2, minY)];
//    }
    //圆角
    if (direction == directionUp) {
        [path addLineToPoint:CGPointMake(offset-width/2, minY)];
        [path addArcWithCenter:CGPointMake(offset, minY - 4.7) radius:2 startAngle:-M_PI_4 * 3 endAngle:-M_PI_4 clockwise:YES];
        [path addLineToPoint:CGPointMake(offset+width/2, minY)];
    }

希望作者能够支撑

**Comment by wwmz** [comment]
> 需求：弹框中的三角形，看起来很不友好
> 
> 办法：我只能修改您的如下代码
> //上边
> [path moveToPoint:CGPointMake(minX+cornerRadius, minY)];
> // //三角形
> // if (direction == directionUp) {
> // [path addLineToPoint:CGPointMake(offset-width/2, minY)];
> // [path addLineToPoint:CGPointMake(offset, minY-height)];
> // [path addLineToPoint:CGPointMake(offset+width/2, minY)];
> // }
> //圆角
> if (direction == directionUp) {
> [path addLineToPoint:CGPointMake(offset-width/2, minY)];
> [path addArcWithCenter:CGPointMake(offset, minY - 4.7) radius:2 startAngle:-M_PI_4 * 3 endAngle:-M_PI_4 clockwise:YES];
> [path addLineToPoint:CGPointMake(offset+width/2, minY)];
> }
> 
> 希望作者能够支撑
可以 下版本更新 确实圆一点会好看些

**Comment by wwmz** [comment]
> 需求：弹框中的三角形，看起来很不友好
> 
> 办法：我只能修改您的如下代码
> //上边
> [path moveToPoint:CGPointMake(minX+cornerRadius, minY)];
> // //三角形
> // if (direction == directionUp) {
> // [path addLineToPoint:CGPointMake(offset-width/2, minY)];
> // [path addLineToPoint:CGPointMake(offset, minY-height)];
> // [path addLineToPoint:CGPointMake(offset+width/2, minY)];
> // }
> //圆角
> if (direction == directionUp) {
> [path addLineToPoint:CGPointMake(offset-width/2, minY)];
> [path addArcWithCenter:CGPointMake(offset, minY - 4.7) radius:2 startAngle:-M_PI_4 * 3 endAngle:-M_PI_4 clockwise:YES];
> [path addLineToPoint:CGPointMake(offset+width/2, minY)];
> }
> 
> 希望作者能够支撑

可以 下版本更新 确实圆一点会好看些

**Comment by ygf-git** [comment]
好的，多谢，非常感谢。更新完麻烦通知我一下

**Comment by ygf-git** [comment]
Multiple methods named 'count' found with mismatched result, parameter type or attributes
@wwmz 嗨，因为要圆角，需要改动到您的代码，因此把WMZDialog拖到工程里，但是报很多方法名重复的错误。
请问有什么解决方案嘛？
或者麻烦帮我更新一个版本

**Comment by wwmz** [comment]
> Multiple methods named 'count' found with mismatched result, parameter type or attributes
> @wwmz 嗨，因为要圆角，需要改动到您的代码，因此把WMZDialog拖到工程里，但是报很多方法名重复的错误。
> 请问有什么解决方案嘛？
> 或者麻烦帮我更新一个版本

哦 应该是你项目里严格限制了类型的转换 今天下午给你发个版

**Comment by ygf-git** [comment]
好的，多谢

**Comment by ygf-git** [comment]
没看到有新版本发布呀

**Comment by wwmz** [comment]
> 没看到有新版本发布呀

还没更新 太忙忘记了 更新了通知你

**Comment by wwmz** [comment]
> 没看到有新版本发布呀

更新了你看看 wAngleRadio default 0 传个2或者3差不多了

**Comment by ygf-git** [comment]
我只能更新到1.2.4的版本

**Comment by ygf-git** [comment]
可以了哈，谢谢
