### ISSUE TITLE
请问自定义弹窗，只能弹出到居中位置吗？

### ISSUE THREAD

**Issue by iOSchuang** [wwmz/WMZDialog#40]
自定义弹窗位置如何调整

**Comment by wwmz** [comment]
> 自定义弹窗位置如何调整

    //重设frame 如果需要改变frame
    .wCustomMainViewSet(^(UIView *mainView) {
        CGRect rect = mainView.frame;
        rect.origin.x+=30;
        rect.size.height+=30;
        mainView.frame = rect;
    })
