### ISSUE TITLE
你好，请问wParentVC现在不能用了吗

### ISSUE THREAD

**Issue by GSSSSSS** [wwmz/WMZDialog#41]
1.2.5版本没有wParentVC属性了，请问怎么控制在指定页面弹出而不是在最上层弹出

**Comment by GSSSSSS** [comment]
找到了，用wStartView方法就可以

**Comment by wwmz** [comment]
> 1.2.5版本没有wParentVC属性了，请问怎么控制在指定页面弹出而不是在最上层弹出

用wParentVC这个会导致循环引用哈 用wStartView就可以在任意视图层弹出了
