### ISSUE TITLE
禁用屏幕旋转，但是WMZDialog会旋转，导致坐标异常。

### ISSUE THREAD

**Issue by ygf-git** [wwmz/WMZDialog#42]

**Comment by ygf-git** [comment]
方便加个联系方式嘛？我可以录屏给你看

**Comment by ygf-git** [comment]
您提供的Demo，Device Orientation设置成只支持Portrait，绝大多数的弹框坐标都会出现问题。
您问要怎么解决呢？

**Comment by wwmz** [comment]
> 您提供的Demo，Device Orientation设置成只支持Portrait，绝大多数的弹框坐标都会出现问题。
> 您问要怎么解决呢？

什么问题 只支持Portrait不是竖屏吗 竖屏为啥会有问题 你把wDeviceDidChange 设为NO试试

**Comment by wwmz** [comment]
> 您提供的Demo，Device Orientation设置成只支持Portrait，绝大多数的弹框坐标都会出现问题。
> 您问要怎么解决呢？

wDeviceDidChange 设为NO

**Comment by wwmz** [comment]
> 您提供的Demo，Device Orientation设置成只支持Portrait，绝大多数的弹框坐标都会出现问题。
> 您问要怎么解决呢？

没问题就自己把这个issuse关了哈

**Comment by ygf-git** [comment]
好的，没问题了。多谢
