### ISSUE TITLE
请问弹窗能否扩展添加阴影

### ISSUE THREAD

**Issue by iOSchuang** [wwmz/WMZDialog#43]
弹出的弹框，是否可以添加阴影，我看开放的api是遮罩层阴影，不知弹窗是否可添加阴影，谢谢

**Comment by wwmz** [comment]
> 弹出的弹框，是否可以添加阴影，我看开放的api是遮罩层阴影，不知弹窗是否可添加阴影，谢谢
适用于没有剪切半圆角的弹框
    .wCustomMainViewSet(^(UIView *mainView) {
        mainView.layer.masksToBounds = NO;
        mainView.layer.shadowColor = [UIColor blackColor].CGColor;
        mainView.layer.shadowOffset = CGSizeMake(0,0);
        mainView.layer.shadowOpacity = 0.5;
        mainView.layer.shadowRadius = 5;
        
    })

**Comment by wwmz** [comment]
> 弹出的弹框，是否可以添加阴影，我看开放的api是遮罩层阴影，不知弹窗是否可添加阴影，谢谢


适用于没有剪切半圆角的弹框
.wCustomMainViewSet(^(UIView *mainView) {
mainView.layer.masksToBounds = NO;
mainView.layer.shadowColor = [UIColor blackColor].CGColor;
mainView.layer.shadowOffset = CGSizeMake(0,0);
mainView.layer.shadowOpacity = 0.5;
mainView.layer.shadowRadius = 5;

})

**Comment by iOSchuang** [comment]
![image](https://user-images.githubusercontent.com/15044460/110614182-0a899680-81cd-11eb-9a6e-1362ffc06179.png)
在tableview上的

**Comment by wwmz** [comment]
> ![image](https://user-images.githubusercontent.com/15044460/110614182-0a899680-81cd-11eb-9a6e-1362ffc06179.png)
> 在tableview上的

哪个type  select吗 是可以的哦 除了那种底部弹出的都行

**Comment by iOSchuang** [comment]
![image](https://user-images.githubusercontent.com/15044460/110618644-e8464780-81d1-11eb-8bbf-571fad7e682e.png)
我设置之后无效，我是在tableview的sectionHeader上弹出的列表

**Comment by wwmz** [comment]
> ![image](https://user-images.githubusercontent.com/15044460/110618644-e8464780-81d1-11eb-8bbf-571fad7e682e.png)
> 我设置之后无效，我是在tableview的sectionHeader上弹出的列表

哦 你是pop这种啊 这种好像这个方法是不行的  要改源码了估计
