### ISSUE TITLE
wEventCloseSet调用多次

### ISSUE THREAD

**Issue by Reliable-D** [wwmz/WMZDialog#44]
```objc
            Dialog().wTypeSet(DialogTypeWrite)
            .wEventOKFinishSet(^(id anyID, id otherData) {
                NSLog(@"finish %@",anyID);
            }).wEventCloseSet(^(id anyID, id otherData) {
                NSLog(@"close %@",anyID);
            }).wEventCancelFinishSet(^(id anyID, id otherData) {
                NSLog(@"cancel %@",anyID);
            })
            //默认内容
            .wWriteDefaultTextSet(@"默认内容")
            //提示文本
            .wPlaceholderSet(@"请输入内容")
            //编辑框最大行数 大于行数则滚动
            .wWirteTextMaxLineSet(1)
            //键盘类型
            .wWirteKeyBoardTypeSet(UIKeyboardTypeDefault)
            .wStart();
```

1. 点击确定按钮
```
2021-04-13 13:41:12.470764+0800 WMZDialog[13151:268534] close 关闭
2021-04-13 13:41:12.472211+0800 WMZDialog[13151:268534] finish 默认内容
2021-04-13 13:41:12.472638+0800 WMZDialog[13151:268534] close 关闭
```
2. 点击取消按钮
```
2021-04-13 13:42:06.452467+0800 WMZDialog[13151:268534] close 关闭
2021-04-13 13:42:06.453379+0800 WMZDialog[13151:268534] cancel 取消
2021-04-13 13:42:06.453591+0800 WMZDialog[13151:268534] close 关闭
```

3. 点击蒙层
```
2021-04-13 13:42:40.986170+0800 WMZDialog[13151:268534] close 关闭
2021-04-13 13:42:40.987132+0800 WMZDialog[13151:268534] close 关闭
```

**Comment by wwmz** [comment]
> ```objc
>             Dialog().wTypeSet(DialogTypeWrite)
>             .wEventOKFinishSet(^(id anyID, id otherData) {
>                 NSLog(@"finish %@",anyID);
>             }).wEventCloseSet(^(id anyID, id otherData) {
>                 NSLog(@"close %@",anyID);
>             }).wEventCancelFinishSet(^(id anyID, id otherData) {
>                 NSLog(@"cancel %@",anyID);
>             })
>             //默认内容
>             .wWriteDefaultTextSet(@"默认内容")
>             //提示文本
>             .wPlaceholderSet(@"请输入内容")
>             //编辑框最大行数 大于行数则滚动
>             .wWirteTextMaxLineSet(1)
>             //键盘类型
>             .wWirteKeyBoardTypeSet(UIKeyboardTypeDefault)
>             .wStart();
> ```
> 
> 1. 点击确定按钮
> 
> ```
> 2021-04-13 13:41:12.470764+0800 WMZDialog[13151:268534] close 关闭
> 2021-04-13 13:41:12.472211+0800 WMZDialog[13151:268534] finish 默认内容
> 2021-04-13 13:41:12.472638+0800 WMZDialog[13151:268534] close 关闭
> ```
> 
> 1. 点击取消按钮
> 
> ```
> 2021-04-13 13:42:06.452467+0800 WMZDialog[13151:268534] close 关闭
> 2021-04-13 13:42:06.453379+0800 WMZDialog[13151:268534] cancel 取消
> 2021-04-13 13:42:06.453591+0800 WMZDialog[13151:268534] close 关闭
> ```
> 
> 1. 点击蒙层
> 
> ```
> 2021-04-13 13:42:40.986170+0800 WMZDialog[13151:268534] close 关闭
> 2021-04-13 13:42:40.987132+0800 WMZDialog[13151:268534] close 关闭
> ```
已修复  pod还没更新哈  想不更新的解决方法可以把wWirteTextMaxLineSet 设置大于1即可
