### ISSUE TITLE
.wWriteDefaultTextSet(@"")会导致高度计算异常，导致placeholder被截断

### ISSUE THREAD

**Issue by Reliable-D** [wwmz/WMZDialog#45]
![Simulator Screen Shot - iPhone 12 - 2021-04-13 at 23 24 38](https://user-images.githubusercontent.com/10044844/114579211-39a19500-9cb0-11eb-95fe-f0af63fc2caf.png)

复线的代码

```swift
            let dialog:WMZDialog = Dialog()
            dialog.wTypeSet()(DialogTypeWrite)
                .wEventOKFinishSet()({(anyId:Any?,otherData:Any?)in
                print("点击确定",anyId as Any);
            })
                .wPlaceholderSet()("请输入名称")
                .wWirteKeyBoardTypeSet()(.numbersAndPunctuation)
                .wWirteTextMaxLineSet()(2)
                .wWriteDefaultTextSet()("")
            _ = dialog.wStart()
```

当前有2个问题

问题1:  issue code似乎在`WMZDialog+Write.m 31 line self.wWriteDefaultText?:@"占位"`,这里应该用`self.wWriteDefaultText.length > 0`来判断, 因为当前我的DefaultText是空字符串

问题2: 我想确认项目中的Block都是Nonnull的吗？
举个例子，我想设置DefaultText, 值作为变量有可能存在或者不存在。因此当issue1存在时，我还可以这样写`.wWriteDefaultTextSet(value?:nil)`，顶多是一个Null Passed的warning。但是换到swift这就是编译失败，因为参数必须是String，不能是Optional类型。所以只能在外层写if else，这也破坏了链式结构，非常的别扭。

**Comment by wwmz** [comment]
> ![Simulator Screen Shot - iPhone 12 - 2021-04-13 at 23 24 38](https://user-images.githubusercontent.com/10044844/114579211-39a19500-9cb0-11eb-95fe-f0af63fc2caf.png)
> 
> 复线的代码
> 
> ```swift
>             let dialog:WMZDialog = Dialog()
>             dialog.wTypeSet()(DialogTypeWrite)
>                 .wEventOKFinishSet()({(anyId:Any?,otherData:Any?)in
>                 print("点击确定",anyId as Any);
>             })
>                 .wPlaceholderSet()("请输入名称")
>                 .wWirteKeyBoardTypeSet()(.numbersAndPunctuation)
>                 .wWirteTextMaxLineSet()(2)
>                 .wWriteDefaultTextSet()("")
>             _ = dialog.wStart()
> ```
> 
> 当前有2个问题
> 
> 问题1: issue code似乎在`WMZDialog+Write.m 31 line self.wWriteDefaultText?:@"占位"`,这里应该用`self.wWriteDefaultText.length > 0`来判断, 因为当前我的DefaultText是空字符串
> 
> 问题2: 我想确认项目中的Block都是Nonnull的吗？
> 举个例子，我想设置DefaultText, 值作为变量有可能存在或者不存在。因此当issue1存在时，我还可以这样写`.wWriteDefaultTextSet(value?:nil)`，顶多是一个Null Passed的warning。但是换到swift这就是编译失败，因为参数必须是String，不能是Optional类型。所以只能在外层写if else，这也破坏了链式结构，非常的别扭。

你外层定义一个变量 直接传入就行啦 不要在在里面 value？:nil
