### ISSUE TITLE
编辑弹窗能添加手动控制窗口是否隐藏的属性？现在校验输入内容不合法想提示用户然后继续编辑，但是窗口直接就关闭了。

### ISSUE THREAD

**Issue by ningmengjean** [wwmz/WMZDialog#49]

**Comment by wwmz** [comment]
> _No description provided._

晚些更新至 1.3.1 (1)新增通用wAutoClose属性 响应库内的自动关闭 default YES 如果设为NO则需要自己调用手动关闭的类方法 closeWithshowView (2) writeType新增 wRegular属性 正则校验规则 default nil 例如 可传入 @{@"reguler":@"^1+[3578]+\d{9}",@"reguletTip":@"请输入正确的手机号"}

**Comment by wwmz** [comment]
更新上去了 我关咯
