### ISSUE TITLE
横屏支持有问题

### ISSUE THREAD

**Issue by heliang219** [wwmz/WMZDialog#50]
demo 模拟器上我横屏运行 然后点分享按钮 如图所示。
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-04 at 16 13 37](https://user-images.githubusercontent.com/795426/120769758-03fe8700-c550-11eb-999e-adab11fbb335.png)

大侠，请问如何解决？

**Comment by wwmz** [comment]
> demo 模拟器上我横屏运行 然后点分享按钮 如图所示。
> ![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-04 at 16 13 37](https://user-images.githubusercontent.com/795426/120769758-03fe8700-c550-11eb-999e-adab11fbb335.png)
> 
> 大侠，请问如何解决？

我后面更新的时候默认把横屏关闭了 要开启wDeviceDidChange

**Comment by wwmz** [comment]
> demo 模拟器上我横屏运行 然后点分享按钮 如图所示。
> ![Simulator Screen Shot - iPhone 12 Pro Max - 2021-06-04 at 16 13 37](https://user-images.githubusercontent.com/795426/120769758-03fe8700-c550-11eb-999e-adab11fbb335.png)
> 
> 大侠，请问如何解决？

你是竖屏运行 然后转横屏？ 还是直接横屏运行？ 直接横屏运行的话 你要去修改默认值咯 wWidth wHeight  这个我没想到 找时间再适配这个直接横屏运行的问题吧

**Comment by heliang219** [comment]
竖屏运行转横屏的话 那就更乱了 这个界面都看不到 你可以试下 你试不出来 我可以录个视频给你

**Comment by wwmz** [comment]
> 竖屏运行转横屏的话 那就更乱了 这个界面都看不到 你可以试下 你试不出来 我可以录个视频给你

竖屏转横屏的适配 后面更新的版本 默认是关闭的 要传wDeviceDidChange为YES

**Comment by heliang219** [comment]
设置了也没效果啊 我直接demo里把你里面的wDeviceDidChange设置为YES的
![截屏2021-06-06 14 37 23](https://user-images.githubusercontent.com/795426/120915150-bfe8bf00-c6d4-11eb-9657-0ca84cf715a0.png)
