### ISSUE TITLE
任意弹出框位置发生错乱

### ISSUE THREAD

**Issue by gaolou** [wwmz/WMZDialog#51]
点击微信右上角，弹出选择框，程序推至后台，再回到前台，弹出框的位置跑到了视图中间去了！

**Comment by wwmz** [comment]
> 点击微信右上角，弹出选择框，程序推至后台，再回到前台，弹出框的位置跑到了视图中间去了！

我用我demo试了 重现不了 怎么可能会变位置啊 这绝对布局来着

**Comment by Jhin-zhou** [comment]
![image](https://user-images.githubusercontent.com/70634881/126455180-848934a5-4946-425b-8b4d-42e46b01cb38.png)
![image](https://user-images.githubusercontent.com/70634881/126455203-e8109626-359b-4510-8775-e4c0172abf53.png)
试过多个机型均能复现

**Comment by wwmz** [comment]
> ![image](https://user-images.githubusercontent.com/70634881/126455458-b0ae3580-6ed0-4359-a83d-5b2cc01a2d30.png)
> 
> ![image](https://user-images.githubusercontent.com/70634881/126455180-848934a5-4946-425b-8b4d-42e46b01cb38.png)
> 
> 试过多个机型均能复现 弹窗出来后直接进入后台不要让弹窗消失 再回到前台 弹窗就会居中了
> 刚最新版试了下,最新1.3.3这个问题已经没了

**Comment by gaolou** [comment]
新版本已经好了！666！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wwmz/WMZDialog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月21日(星期三) 下午4:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wwmz/WMZDialog] 任意弹出框位置发生错乱 (#51)





  

 

 
试过多个机型均能复现 弹窗出来后直接进入后台不要让弹窗消失 再回到前台 弹窗就会居中了
 刚最新版试了下,最新1.3.3这个问题已经没了
