### ISSUE TITLE
【BUG】在swift中会崩溃

### ISSUE THREAD

**Issue by lvjesus** [wwmz/WMZDialog#56]
![image](https://user-images.githubusercontent.com/13743043/149690305-5ac103c4-234c-4707-a765-62aeb9853aad.png)

**Comment by lvjesus** [comment]
在AppDelegate中增加
var window: UIWindow?

**Comment by wwmz** [comment]
> ![image](https://user-images.githubusercontent.com/13743043/149690305-5ac103c4-234c-4707-a765-62aeb9853aad.png)

Appdeleagte里增加 window:UIWindow
