### ISSUE TITLE
怎么添加时间限制

### ISSUE THREAD

**Issue by wangpt** [wwmz/WMZDialog#6]
日期时间弹框如何限制的最大时间和最小时间？

**Comment by wwmz** [comment]
暂时没这个属性 需要我增加哦

**Comment by wwmz** [comment]
新增  wMinDate 最小时间  
         wMaxDate 最大时间 
         数据类型为NSDate 超出的时间隐藏 
修改输出的格式 传入什么格式 输出就为什么格式

**Comment by wangpt** [comment]
你好，设置最大时间为当天时，限制不起作用
比如设置wMaxDate为12月26日，日历控件仍可选择12月27日或者之后的日期

**Comment by wwmz** [comment]
你说的type是日历 还是 日期的？？

**Comment by wwmz** [comment]
不知道你说的日历还是日期的 日期的修改了 日历的也支持最大最小时间了 cocopod没更新 GitHub代码更新

**Comment by wangpt** [comment]
已经可以了，我说的是日期的，多谢大佬
