### ISSUE TITLE
大侠，我不要文字，图片位置如何居中显示？

### ISSUE THREAD

**Issue by heliang219** [wwmz/WMZDialog#60]
![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-09 at 11 14 32](https://user-images.githubusercontent.com/795426/157365872-559efbb4-f718-42fd-b460-873a3a076e58.png)

**Comment by heliang219** [comment]
还有个问题 就是我点击了单个按钮 如何不消失这个menu 只有点击背景我才消失这个menu

**Comment by wwmz** [comment]
> ![Simulator Screen Shot - iPhone 13 Pro Max - 2022-03-09 at 11 14 32](https://user-images.githubusercontent.com/795426/157365872-559efbb4-f718-42fd-b460-873a3a076e58.png)

目前不支持哦 等我这两天更新一下适配一下这种情况哈
