### ISSUE TITLE
集成后，无效，无反应

### ISSUE THREAD

**Issue by ange521** [wwmz/WMZDialog#61]
将 cocoapods 更新至最新版本.
在 Podfile 中添加 pod 'WMZDialog'
执行 pod install 或 pod update。
导入 #import "WMZDialog.h"。
按照这样的配置，没有反应，没有弹窗出来，我查了很多demo
但是还是不行

**Comment by wwmz** [comment]
> 将 cocoapods 更新至最新版本. 在 Podfile 中添加 pod 'WMZDialog' 执行 pod install 或 pod update。 导入 #import "WMZDialog.h"。 按照这样的配置，没有反应，没有弹窗出来，我查了很多demo 但是还是不行

应该是你的window没设置 你使用wStartView 传入你能获取的window或者view即可
