### ISSUE TITLE
 通过Masonry布局能不能增加一个刷新布局的接口

### ISSUE THREAD

**Issue by icNaoki** [wwmz/WMZDialog#62]
现在有个需求就是我弹出之后，需要动态改变上面的显示内容，然后整个布局也需要跟着改变

**Comment by wwmz** [comment]
> 现在有个需求就是我弹出之后，需要动态改变上面的显示内容，然后整个布局也需要跟着改变

下个版本增加

**Comment by wwmz** [comment]
使用- (void)reSetMainViewFrame:(CGRect)frame;
