### ISSUE TITLE
Toast弹框不影响界面操作

### ISSUE THREAD

**Issue by PengSiSi** [wwmz/WMZDialog#66]
DialogTypeAuto弹框怎么设置不影响界面操作呢？

**Comment by wwmz** [comment]
> DialogTypeAuto弹框怎么设置不影响界面操作呢？

什么意思呢？你是要弹窗出来 然后还能继续操作吗

**Comment by PengSiSi** [comment]
是的是的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月27日(周一) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wwmz/WMZDialog] Toast弹框不影响界面操作 (Issue #66)




  
DialogTypeAuto弹框怎么设置不影响界面操作呢？
  
什么意思呢？你是要弹窗出来 然后还能继续操作吗

**Comment by PengSiSi** [comment]
仅toast提示类的弹窗不影响点击等操作



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月27日(周一) 上午9:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wwmz/WMZDialog] Toast弹框不影响界面操作 (Issue #66)




  
DialogTypeAuto弹框怎么设置不影响界面操作呢？
  
什么意思呢？你是要弹窗出来 然后还能继续操作吗

**Comment by wwmz** [comment]
> 仅toast提示类的弹窗不影响点击等操作
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2022年6月27日(周一) 上午9:50 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wwmz/WMZDialog] Toast弹框不影响界面操作 (Issue #66) DialogTypeAuto弹框怎么设置不影响界面操作呢？ 什么意思呢？你是要弹窗出来 然后还能继续操作吗 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

下个版本加

**Comment by wwmz** [comment]
新增wUserInteractionEnabled  设置为NO 且需要使用wStartView弹出 即可不影响
