### ISSUE TITLE
拾趣器希望可以有单列切换事件

### ISSUE THREAD

**Issue by 522011796** [wwmz/WMZDialog#67]
拾趣器希望可以有单列切换事件，这样可以根据切换后的数据进行某些操作

**Comment by wwmz** [comment]
> 拾趣器希望可以有单列切换事件，这样可以根据切换后的数据进行某些操作
什么场景呢？举个例子

**Comment by wwmz** [comment]
如果需要多列操作 类似选省市区的 可以使用地区弹窗 传入自定义数据即可
