### ISSUE TITLE
下拉无限级菜单弹窗bug

### ISSUE THREAD

**Issue by Monster9322** [wwmz/WMZDialog#7]
二级以上，初始数据时数组首位的children数组若为空将会崩溃

**Comment by wwmz** [comment]
数据源是什么样的 看看

**Comment by Monster9322** [comment]
> 数据源是什么样的 看看
其实就是你的demo里的getArr2方法的数据1和数据2互换位置
![bug](https://user-images.githubusercontent.com/14042116/71537629-b7c21700-2959-11ea-9fd6-b8da0f47bcce.jpg)

**Comment by wwmz** [comment]
好的 已修改

**Comment by Monster9322** [comment]
> 好的 已修改

依然是崩溃，看下图。。是这个位置越组了
![1577763705835](https://user-images.githubusercontent.com/14042116/71609350-99ab1f80-2bc2-11ea-8cfd-c8e147a5ccc6.jpg)

**Comment by Monster9322** [comment]
> 好的 已修改

pod 导入最新的1.0.6版本，并没有修复该bug。DEMO上的已经修正了。是要手动导入吗？

**Comment by wwmz** [comment]
我没更新呢 你手动吧
