### ISSUE TITLE
默认弹窗设置wTextAlignment无效.

### ISSUE THREAD

**Issue by maoweipengft** [wwmz/WMZDialog#70]
case 1:{
            Dialog()
            
            //出现动画
            .wShowAnimationSet(AninatonZoomIn)
            //消失动画
            .wHideAnimationSet(AninatonZoomOut)
            .wEventCancelFinishSet(^(id anyID, id otherData) {})
            .wMessageSet(@"这里是内容这里是内容这里是内容\n这里是内容\n这里是内容这里是内容这里是内容这里是内容这里是内容这里是内容这里是内容这里是内容\n这里是内容\n")
            .wTitleSet(@"这是一条标题\n这是一条标题")
            .wOKTitleSet(@"好的")
            .wCancelTitleSet(@"我知道了")
            .wTextAlignmentSet(NSTextAlignmentLeft)
            .wMessageColorSet(DialogColor(0x333333))
            .wTitleColorSet(DialogColor(0x666666))
            .wOKColorSet([UIColor orangeColor])
            .wCancelColorSet([UIColor redColor])
            .wTitleFontSet(15)
            .wTypeSet(DialogTypeNornal).wStart();
        }
            break;

**Comment by maoweipengft** [comment]
已解决，在"WMZDialogNormal.m"的setParam方法中添加 self.textLabel.textAlignment = param.wTextAlignment;

**Comment by wwmz** [comment]
> wTextAlignmentSet

wTextAlignmentSet不是设置这里的哦  你如果要设置这个可以在wCustomMessageLa里设置哦
