### ISSUE TITLE
可否自定义设置弹窗内容的attributedText富文本格式.

### ISSUE THREAD

**Issue by maoweipengft** [wwmz/WMZDialog#71]
可否自定义设置弹窗内容的attributedText富文本格式.
(需求：每行与行的间距,段落与段落的间距)

**Comment by wwmz** [comment]
> 可否自定义设置弹窗内容的attributedText富文本格式. (需求：每行与行的间距,段落与段落的间距)

    .wCustomMessageLaSet(^(UILabel *messageLa) {
        messageLa.attributedText = NSMutableAttributedString.new;
    })
    .wHeightSet(111)  要算出高度然后设置一下wHeight 或者 调用dialog的 reSetMainViewFrame 方法重置一下  这个没有自动适配自定义文本高度哦

**Comment by maoweipengft** [comment]
好的，不过还是希望富文本也能自动计算高度

**Comment by wwmz** [comment]
> 好的，不过还是希望富文本也能自动计算高度,毕竟苹果默认的行间距还是不那么美观

已增加适配 直接传入富文本即可
