### ISSUE TITLE
富文本设置了setLineSpacing 计算高度问题!

### ISSUE THREAD

**Issue by maoweipengft** [wwmz/WMZDialog#73]
NSString *contentStr = @"这是一个内容\n这是一个内容\n这是一个内容这是一个内容\n这是一个内容这是一个内容";
            NSMutableAttributedString * messageStr = [[NSMutableAttributedString alloc] initWithString:contentStr];
            [paragraphStyle setLineSpacing:5];
            [messageStr addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, [contentStr length])];

如上代码，设置setLineSpacing之后不能获得正确的内容高度.

**Comment by maoweipengft** [comment]
<img width="452" alt="image" src="https://user-images.githubusercontent.com/33150211/192928775-6d630035-7272-44c2-9f8f-a0dfa42e232d.png">

**Comment by wwmz** [comment]
> NSString *contentStr = @"这是一个内容\n这是一个内容\n这是一个内容这是一个内容\n这是一个内容这是一个内容"; NSMutableAttributedString * messageStr = [[NSMutableAttributedString alloc] initWithString:contentStr]; [paragraphStyle setLineSpacing:5]; [messageStr addAttribute:NSParagraphStyleAttributeName value:paragraphStyle range:NSMakeRange(0, [contentStr length])];
> 
> 如上代码，设置setLineSpacing之后不能获得正确的内容高度.

要设置一下NSFontAttributeName吧
