### ISSUE TITLE
请问如何修改弹窗的背景颜色呢？

### ISSUE THREAD

**Issue by xiaoyao20084321** [wwmz/WMZDialog#77]
请问如何修改弹窗的背景颜色呢，设置wMainBackColor后，只有三角颜色变成想要修改的颜色了，弹窗背景图还是白色
<img width="759" alt="image" src="https://user-images.githubusercontent.com/10344550/200470744-2a63dae2-c32c-4ee4-b1da-bfa023d7bec0.png">
<img width="249" alt="image" src="https://user-images.githubusercontent.com/10344550/200470984-3d31e41c-0fc8-4be9-8fb4-176214555c77.png">

**Comment by xiaoyao20084321** [comment]
必须得自定义cell嘛？

**Comment by wwmz** [comment]
> 必须得自定义cell嘛？

是的 你自定义个cell  设置一下cell的背景颜色即可

**Comment by xiaoyao20084321** [comment]
好吧，不过我建议直接暴露出来一个属性。。不然就修改一下颜色，结果还得自定义一个cell， 感觉有点大题小做了。

**Comment by wwmz** [comment]
> 好吧，不过我建议直接暴露出来一个属性。。不然就修改一下颜色，结果还得自定义一个cell， 感觉有点大题小做了。

可以的 下版本增加个cell背景颜色设置就可以了

**Comment by xiaoyao20084321** [comment]
> > 好吧，不过我建议直接暴露出来一个属性。。不然就修改一下颜色，结果还得自定义一个cell， 感觉有点大题小做了。
> 
> 可以的 下版本增加个cell背景颜色设置就可以了

好的，老哥威武霸气， 你看我现在close这个issue呢还是等你发新版后，你来close呢
