### ISSUE TITLE
请问如何修改弹窗圆角的大小呢？

### ISSUE THREAD

**Issue by xiaoyao20084321** [wwmz/WMZDialog#78]
作者你好，只找到了可以设置为哪里圆角属性（比如全部圆角），没找到设置圆角的大小，感觉默认的圆角有点大了。
<img width="651" alt="image" src="https://user-images.githubusercontent.com/10344550/200471544-815e52db-9529-4b66-acf2-73ae82bf4f38.png">

<img width="219" alt="image" src="https://user-images.githubusercontent.com/10344550/200471481-ef9f9a4c-97f9-4510-8373-b38a8b5ca928.png">

**Comment by wwmz** [comment]
> 作者你好，只找到了可以设置为哪里圆角属性（比如全部圆角），没找到设置圆角的大小，感觉默认的圆角有点大了。 <img alt="image" width="651" src="https://user-images.githubusercontent.com/10344550/200471544-815e52db-9529-4b66-acf2-73ae82bf4f38.png">
> 
> <img alt="image" width="219" src="https://user-images.githubusercontent.com/10344550/200471481-ef9f9a4c-97f9-4510-8373-b38a8b5ca928.png">

wMainRadius

**Comment by xiaoyao20084321** [comment]
好的，我的问题。。我在源码里找了半天没找到。。。我以为没有
