### ISSUE TITLE
DialogTypeSheet，无法多行显示吗？

### ISSUE THREAD

**Issue by souls-shaohui** [wwmz/WMZDialog#79]
DialogTypeSheet，可以有办法设置成多行显示吗？现在只能单行展示

**Comment by wwmz** [comment]
> DialogTypeSheet，可以有办法设置成多行显示吗？现在只能单行展示

多行显示是什么？截个图看看

**Comment by souls-shaohui** [comment]
![Uploading image.png…]()
类似这种，就是选项里支持自动换行

**Comment by souls-shaohui** [comment]
<img width="486" alt="image" src="https://user-images.githubusercontent.com/15151335/201043153-bad660b9-e203-4f7b-b9ed-fc3b3893bfa8.png">

**Comment by wwmz** [comment]
> <img alt="image" width="486" src="https://user-images.githubusercontent.com/15151335/201043153-bad660b9-e203-4f7b-b9ed-fc3b3893bfa8.png">

哦 目前可能没支持 版本支持 你目前可以使用自定义cell就可以实现了

**Comment by wwmz** [comment]
下版本支持

**Comment by souls-shaohui** [comment]
好的，感谢。那我先用自定义cell

**Comment by wwmz** [comment]
fix 1.4.88

**Comment by souls-shaohui** [comment]
两行时候可以，超过两行，高度计算有问题。

<img width="486" alt="image" src="https://user-images.githubusercontent.com/15151335/202986394-5221261e-3de3-4504-881d-7c33cfea07ea.png">



> fix 1.4.88

**Comment by wwmz** [comment]
> 两行时候可以，超过两行，高度计算有问题。
> 
> <img alt="image" width="486" src="https://user-images.githubusercontent.com/15151335/202986394-5221261e-3de3-4504-881d-7c33cfea07ea.png">
> 
> > fix 1.4.88

高度目前只支持固定的哈 通过wCellHeight控制的 不是动态的 不然还要算tableView的高度 有点麻烦
