### ISSUE TITLE
swift能调用吗

### ISSUE THREAD

**Issue by HZZJL** [wwmz/WMZDialog#8]
swift能调用吗

**Comment by wwmz** [comment]
可以吧 桥接

**Comment by HZZJL** [comment]
Argument passed to call that takes no arguments

**Comment by wwmz** [comment]
可以啊 我刚才桥接试了下。。没这问题啊 你是不是弄错啥了

**Comment by HZZJL** [comment]
代码能贴下吗？看看怎么调用的，谢谢

**Comment by wwmz** [comment]
这时候oc的链式使用不了 只能用回初始的属性设置
例如普通弹窗

        let alert:WMZDialog = Dialog()
        alert.wTitle = "标题1"
        alert.wMessage = "内容2"
        alert.wEventOKFinish = {(anyId:Any?,otherData:Any?)in
            print("点击确定",anyId as Any);
        }
        alert.wStart();
代码块要自己转成swift的

**Comment by HZZJL** [comment]
明白了，一直用的链式调用，谢谢
