### ISSUE TITLE
当 wTypeSet(DialogTypeDatePicker) 时候如何设置文字不要这种凹凸的对齐方式？

### ISSUE THREAD

**Issue by maoweipengft** [wwmz/WMZDialog#82]
<img width="398" alt="image" src="https://user-images.githubusercontent.com/33150211/206674587-edccb7d9-d0cc-4b74-b7d1-03b11f28b3cf.png">

**Comment by maoweipengft** [comment]
我希望文字可以都垂直居中

**Comment by maoweipengft** [comment]
你好，请问可以设置时间选择器的堆砌方式吗？

**Comment by wwmz** [comment]
> 你好，请问可以设置日期选择器中文字的对其方式方式吗？就是不管是不是选中，文字都对其

不可以

**Comment by maoweipengft** [comment]
明白了
