### ISSUE TITLE
提个小需求：能否增加设置语言

### ISSUE THREAD

**Issue by chuzhaozhi** [wwmz/WMZDialog#85]
非常感谢大佬的轮子，能否增加个设置语言的属性，设置英语或者中文

**Comment by wwmz** [comment]
> 非常感谢大佬的轮子，能否增加个设置语言的属性，设置英语或者中文

里面显示的内容都是你传进去的吧。。传进去的时候国际化就好了呀

**Comment by chuzhaozhi** [comment]
例如弹出的日历呢

**Comment by wwmz** [comment]
> 例如弹出的日历呢

顶部的周一 周二 这个也是可以外部传进去的 其他的都是可以的 除了农历没有 这个可以用自定义cell解决

**Comment by chuzhaozhi** [comment]
好的，谢谢
