### ISSUE TITLE
BUG了，最小时间设置成当前时间，1月7号，变成了1月13号

### ISSUE THREAD

**Issue by Gantios** [wwmz/WMZDialog#9]
NSCalendar *gregorian = [[NSCalendar alloc] initWithCalendarIdentifier:NSCalendarIdentifierGregorian];
        NSDateComponents *dateComponents = [[NSDateComponents alloc] init];
        [dateComponents setYear:+20];
        [dateComponents setMonth:-4];
        NSDate *maxDate = [gregorian dateByAddingComponents:dateComponents toDate:[NSDate date] options:0];

NSDate *minDate = [NSDate date];

Dialog()
        .wEventOKFinishSet(^(id anyID, id otherData) {
            NSLog(@"选中 %@ %@",anyID,otherData);
        })
        //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
        .wDateTimeTypeSet(@"yyyy年MM月dd日")
//        .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
        //最小时间
        .wMinDateSet(minDate)
        //最大时间
        .wMaxDateSet(maxDate)
        //此时最好关闭循环防止出错 
        .wPickRepeatSet(NO)
        .wTypeSet(DialogTypeDatePicker)
        .wStart();

**Comment by wwmz** [comment]
你是cocopod的 还是直接拉的 ？我试了下demo运行没问题哦  还是1月7号  我可能pod没更新 你下载demo看看？

**Comment by wwmz** [comment]
看了下代码提交记录 确实是pod1.0.6版本没更新这个bug呢 你更新到1.0.7试下哦 我同步了

**Comment by Gantios** [comment]
我是直接从 github 打包下载的，发现还是会的出现BUG，最小时间为  [NSDate date] 也即是现在，还会出现类似问题，直接用demo改了2行代码，代码如下：
NSDate *minDate = [NSDate date];
        NSDate *maxDate = [[NSDate date] dateByAddingTimeInterval:3600*24*356*8];


        Dialog()
        .wEventOKFinishSet(^(id anyID, id otherData) {
            NSLog(@"选中 %@ %@",anyID,otherData);
        })
        //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
        .wDateTimeTypeSet(@"yyyy年MM月dd日")
//        .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
        //最小时间
        .wMinDateSet(minDate)
        //最大时间
        .wMaxDateSet(maxDate)
        //此时最好关闭循环防止出错 
        .wPickRepeatSet(NO)
        .wTypeSet(DialogTypeDatePicker)
        .wStart();
        return;

**Comment by Gantios** [comment]
NSDate minDate = [NSDate date];
NSDate maxDate = [[NSDate date] dateByAddingTimeInterval:360024356*8];

**Comment by Gantios** [comment]
NSDate minDate = [NSDate date];
NSDate maxDate = [[NSDate date] dateByAddingTimeInterval:360024356*8];

**Comment by wwmz** [comment]
我知道什么问题了 已解决 代码更新了

**Comment by Gantios** [comment]
1.1.0,又出现了

**Comment by Gantios** [comment]
NSDate *minDate = [NSDate date];
NSDate *maxDate = [[NSDate date] dateByAddingTimeInterval:3600 * 24 * 356 * 8];
Dialog()
.wEventOKFinishSet(^(id anyID, id otherData) {
NSLog(@"选中 %@ %@",anyID,otherData);
})
//年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
.wDateTimeTypeSet(@"yyyy年MM月dd日")
// .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
//最小时间
.wMinDateSet(minDate)
//最大时间
.wMaxDateSet(maxDate)
//此时最好关闭循环防止出错
.wPickRepeatSet(NO)
.wTypeSet(DialogTypeDatePicker)
.wStart();
return;

**Comment by wwmz** [comment]
> NSDate *minDate = [NSDate date];
> NSDate *maxDate = [[NSDate date] dateByAddingTimeInterval:3600 * 24 * 356 * 8];
> Dialog()
> .wEventOKFinishSet(^(id anyID, id otherData) {
> NSLog(@"选中 %@ %@",anyID,otherData);
> })
> //年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
> .wDateTimeTypeSet(@"yyyy年MM月dd日")
> // .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
> //最小时间
> .wMinDateSet(minDate)
> //最大时间
> .wMaxDateSet(maxDate)
> //此时最好关闭循环防止出错
> .wPickRepeatSet(NO)
> .wTypeSet(DialogTypeDatePicker)
> .wStart();

有什么问题吗 最小时间不是4月9日吗 我刚才运行了一下

**Comment by Gantios** [comment]
NSDate *minDate = [NSDate date];
NSDate *maxDate = [[NSDate date] dateByAddingTimeInterval:3600 * 24 * 356 * 8];
Dialog()
.wEventOKFinishSet(^(id anyID, id otherData) {
NSLog(@"选中 %@ %@",anyID,otherData);
})
//年月日时分秒|年月日|年月| 的格式 设置时间限制才有效 其余没有具体时间的约束无效
.wDateTimeTypeSet(@"yyyy年MM月dd日")
// .wDateTimeTypeSet(@"yyyy-MM-dd HH:mm:ss")
//最小时间
.wMinDateSet(minDate)
//最大时间
.wMaxDateSet(maxDate)
//此时最好关闭循环防止出错
.wPickRepeatSet(NO)
.wTypeSet(DialogTypeDatePicker)
.wStart();
