### ISSUE TITLE
自定义View实现了WMZCustomPrototol

### ISSUE THREAD

**Issue by Gaozn** [wwmz/WMZDialog#90]
为什么在你的项目里我设置全屏的代码 没有存在安全区域 view占得是全屏，而在我项目里就是从安全区域开始布局的，我应该设置什么吗？
/// 所处的frame位置
- (CGRect)mz_setupRect{
    [self layoutIfNeeded];
    return UIScreen.mainScreen.bounds;
}

**Comment by wwmz** [comment]
> 为什么在你的项目里我设置全屏的代码 没有存在安全区域 view占得是全屏，而在我项目里就是从安全区域开始布局的，我应该设置什么吗？ /// 所处的frame位置
> 
> * (CGRect)mz_setupRect{
>   [self layoutIfNeeded];
>   return UIScreen.mainScreen.bounds;
>   }

这个要看你startView是哪个哦
