### ISSUE TITLE
亲，1.3到1.4这样大量变动，我会谢的呀....

### ISSUE THREAD

**Issue by HuangYanQi** [wwmz/WMZDialog#92]
1.3到1.4api改动太多，旧代码要做大量变动，或者保持版本....项目中如果用1.3旧代码的不建议升级，变动太多

**Comment by wwmz** [comment]
> 1.3到1.4api改动太多，旧代码要做大量变动，或者保持版本....项目中如果用1.3旧代码的不建议升级，变动太多

没有吧 我记得有兼容的
